"""Persistent ChromaDB storage for ASHA Sahaayak document embeddings.

Embeddings are always generated by :mod:`rag.embeddings`; ChromaDB is used
only for durable vector storage and nearest-neighbour search.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import TYPE_CHECKING, Any, Iterable, Mapping, Sequence
from uuid import uuid4

import chromadb
from langchain_core.documents import Document

import config
from rag.embeddings import generate_embeddings, generate_query_embedding
from utils.helpers import get_logger

if TYPE_CHECKING:
    from chromadb.api.models.Collection import Collection


logger = get_logger("RAG.VectorStore")

_EMBEDDING_MODEL_METADATA_KEY = "asha_embedding_model"
_INTERNAL_DOCUMENT_METADATA_KEY = "_asha_embedding_model"
_DEFAULT_BATCH_SIZE = 128


class VectorStoreConfigurationError(RuntimeError):
    """Raised when a persisted collection uses an incompatible model."""


def _resolve_persist_directory(persist_directory: str | Path | None) -> Path:
    directory = Path(persist_directory or config.CHROMA_PERSIST_DIR).resolve()
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def _validate_collection(collection: Collection) -> None:
    metadata = collection.metadata or {}
    stored_model = metadata.get(_EMBEDDING_MODEL_METADATA_KEY)
    if stored_model is None:
        raise VectorStoreConfigurationError(
            f"Chroma collection '{collection.name}' does not declare its "
            "embedding model. Create it with create_vector_store()."
        )
    if stored_model != config.EMBEDDING_MODEL:
        raise VectorStoreConfigurationError(
            f"Chroma collection '{collection.name}' uses embedding model "
            f"'{stored_model}', but the application is configured for "
            f"'{config.EMBEDDING_MODEL}'."
        )


def _sanitize_metadata(metadata: Mapping[str, Any]) -> dict[str, str | int | float | bool]:
    """Convert LangChain metadata into Chroma-compatible scalar values."""
    sanitized: dict[str, str | int | float | bool] = {}
    for raw_key, value in metadata.items():
        key = str(raw_key)
        if value is None:
            continue
        if isinstance(value, bool):
            sanitized[key] = value
        elif isinstance(value, int):
            sanitized[key] = value
        elif isinstance(value, float):
            sanitized[key] = value if math.isfinite(value) else str(value)
        elif isinstance(value, str):
            sanitized[key] = value
        elif isinstance(value, Path):
            sanitized[key] = str(value)
        else:
            # Chroma metadata values are scalar. JSON retains useful structure
            # for lists and mappings while remaining queryable as a string.
            sanitized[key] = json.dumps(
                value,
                ensure_ascii=False,
                sort_keys=True,
                default=str,
            )

    # This marker ensures metadata is never empty (unsupported by some Chroma
    # releases) and records which model produced each vector.
    sanitized[_INTERNAL_DOCUMENT_METADATA_KEY] = config.EMBEDDING_MODEL
    return sanitized


def _restore_metadata(metadata: Mapping[str, Any] | None) -> dict[str, Any]:
    restored = dict(metadata or {})
    restored.pop(_INTERNAL_DOCUMENT_METADATA_KEY, None)
    return restored


def _validate_documents(documents: Iterable[Document]) -> list[Document]:
    materialized = list(documents)
    if any(not isinstance(document, Document) for document in materialized):
        raise TypeError("Every item must be a langchain Document.")
    if any(not document.page_content.strip() for document in materialized):
        raise ValueError("Documents with empty or whitespace-only content cannot be saved.")
    return materialized


def _validate_ids(ids: Sequence[str] | None, document_count: int) -> list[str]:
    record_ids = list(ids) if ids is not None else [str(uuid4()) for _ in range(document_count)]
    if len(record_ids) != document_count:
        raise ValueError("The number of ids must match the number of documents.")
    if any(not isinstance(record_id, str) or not record_id.strip() for record_id in record_ids):
        raise ValueError("Every document id must be a non-empty string.")
    if len(set(record_ids)) != len(record_ids):
        raise ValueError("Document ids must be unique within a save operation.")
    return record_ids


def create_vector_store(
    *,
    persist_directory: str | Path | None = None,
    collection_name: str = config.CHROMA_COLLECTION_NAME,
) -> Collection:
    """Create or open the configured persistent ChromaDB collection."""
    if not collection_name.strip():
        raise ValueError("collection_name must be a non-empty string.")

    directory = _resolve_persist_directory(persist_directory)
    client = chromadb.PersistentClient(path=str(directory))
    collection = client.get_or_create_collection(
        name=collection_name,
        metadata={
            _EMBEDDING_MODEL_METADATA_KEY: config.EMBEDDING_MODEL,
            "description": "ASHA Sahaayak knowledge-base embeddings",
        },
        embedding_function=None,
    )
    _validate_collection(collection)
    logger.info(
        "Chroma collection '%s' ready at %s (%d records)",
        collection_name,
        directory,
        collection.count(),
    )
    return collection


def load_vector_store(
    *,
    persist_directory: str | Path | None = None,
    collection_name: str = config.CHROMA_COLLECTION_NAME,
) -> Collection:
    """Load an existing persistent ChromaDB collection.

    Unlike :func:`create_vector_store`, this function does not silently create
    a missing collection; Chroma's not-found exception is allowed to surface.
    """
    if not collection_name.strip():
        raise ValueError("collection_name must be a non-empty string.")

    directory = _resolve_persist_directory(persist_directory)
    client = chromadb.PersistentClient(path=str(directory))
    collection = client.get_collection(
        name=collection_name,
        embedding_function=None,
    )
    _validate_collection(collection)
    logger.info(
        "Loaded Chroma collection '%s' from %s (%d records)",
        collection_name,
        directory,
        collection.count(),
    )
    return collection


def save_documents(
    documents: Iterable[Document],
    vector_store: Collection | None = None,
    *,
    ids: Sequence[str] | None = None,
    batch_size: int = _DEFAULT_BATCH_SIZE,
) -> list[str]:
    """Generate embeddings and persist documents to ChromaDB.

    ``upsert`` makes caller-supplied IDs safe to reuse when rebuilding an
    index. Generated IDs are UUIDs and are returned to the caller.
    """
    materialized = _validate_documents(documents)
    if not materialized:
        return []
    if batch_size <= 0:
        raise ValueError("batch_size must be greater than zero.")

    collection = vector_store if vector_store is not None else create_vector_store()
    _validate_collection(collection)
    record_ids = _validate_ids(ids, len(materialized))

    for start in range(0, len(materialized), batch_size):
        batch = materialized[start : start + batch_size]
        batch_ids = record_ids[start : start + batch_size]
        texts = [document.page_content for document in batch]
        embeddings = generate_embeddings(texts)
        if len(embeddings) != len(batch):
            raise RuntimeError("Embedding generation returned an unexpected vector count.")

        collection.upsert(
            ids=batch_ids,
            embeddings=embeddings,
            documents=texts,
            metadatas=[_sanitize_metadata(document.metadata) for document in batch],
        )

    logger.info(
        "Saved %d documents to Chroma collection '%s'",
        len(materialized),
        collection.name,
    )
    return record_ids


def similarity_search(
    query: str,
    k: int = config.TOP_K_RESULTS,
    *,
    vector_store: Collection | None = None,
    where: Mapping[str, Any] | None = None,
) -> list[Document]:
    """Return the ``k`` documents most similar to a text query.

    Chroma's distance and record ID are added to each result's metadata as
    ``_chroma_distance`` and ``_chroma_id`` for observability.
    """
    if not isinstance(query, str):
        raise TypeError("query must be a string.")
    if not query.strip():
        raise ValueError("query must not be empty or whitespace-only.")
    if k <= 0:
        raise ValueError("k must be greater than zero.")

    collection = vector_store if vector_store is not None else load_vector_store()
    _validate_collection(collection)
    record_count = collection.count()
    if record_count == 0:
        return []

    query_embedding = generate_query_embedding(query)
    query_arguments: dict[str, Any] = {
        "query_embeddings": [query_embedding],
        "n_results": min(k, record_count),
        "include": ["documents", "metadatas", "distances"],
    }
    if where is not None:
        query_arguments["where"] = dict(where)

    results = collection.query(**query_arguments)
    documents = (results.get("documents") or [[]])[0]
    metadatas = (results.get("metadatas") or [[]])[0]
    distances = (results.get("distances") or [[]])[0]
    result_ids = (results.get("ids") or [[]])[0]

    matches: list[Document] = []
    for index, content in enumerate(documents):
        if content is None:
            continue
        metadata = _restore_metadata(
            metadatas[index] if index < len(metadatas) else None
        )
        if index < len(result_ids):
            metadata["_chroma_id"] = result_ids[index]
        if index < len(distances) and distances[index] is not None:
            metadata["_chroma_distance"] = float(distances[index])
        matches.append(Document(page_content=content, metadata=metadata))

    return matches


__all__ = [
    "VectorStoreConfigurationError",
    "create_vector_store",
    "load_vector_store",
    "save_documents",
    "similarity_search",
]
